
declare module Blockly.geras {

    class PathObject extends PathObject__Class { }
    /** Fake class which should be extended to avoid inheriting static properties */
    class PathObject__Class extends Blockly.blockRendering.PathObject__Class  { 
    
            /**
             * An object that handles creating and setting each of the SVG elements
             * used by the renderer.
             * @param {!SVGElement} root The root SVG element.
             * @param {!Blockly.Theme.BlockStyle} style The style object to use for
             *     colouring.
             * @param {!Blockly.geras.ConstantProvider} constants The renderer's constants.
             * @constructor
             * @extends {Blockly.blockRendering.PathObject}
             * @package
             */
            constructor(root: SVGElement, style: Blockly.Theme.BlockStyle, constants: Blockly.geras.ConstantProvider);
    
            /**
             * The renderer's constant provider.
             * @type {!Blockly.geras.ConstantProvider}
             */
            constants: Blockly.geras.ConstantProvider;
    
            /**
             * The dark path of the block.
             * @type {SVGElement}
             * @package
             */
            svgPathDark: SVGElement;
    
            /**
             * The primary path of the block.
             * @type {!SVGElement}
             * @package
             */
            svgPath: SVGElement;
    
            /**
             * The light path of the block.
             * @type {SVGElement}
             * @package
             */
            svgPathLight: SVGElement;
    
            /**
             * The colour of the dark path on the block in '#RRGGBB' format.
             * @type {string}
             * @package
             */
            colourDark: string;
    
            /**
             * The style object to use when colouring block paths.
             * @type {!Blockly.Theme.BlockStyle}
             * @package
             */
            style: Blockly.Theme.BlockStyle;
    
            /**
             * Set the highlight path generated by the renderer onto the SVG element.
             * @param {string} highlightPath The highlight path.
             * @package
             */
            setHighlightPath(highlightPath: string): void;
    } 
    
}
