
declare module Blockly.blockRendering {

    interface IPathObject {
    
        /**
          * The primary path of the block.
          * @type {!SVGElement}
          */
        svgPath: SVGElement;
    
        /**
          * The renderer's constant provider.
          * @type {!Blockly.blockRendering.ConstantProvider}
          */
        constants: Blockly.blockRendering.ConstantProvider;
    
        /**
          * The primary path of the block.
          * @type {!Blockly.Theme.BlockStyle}
          */
        style: Blockly.Theme.BlockStyle;
    
        /**
          * Holds the cursors svg element when the cursor is attached to the block.
          * This is null if there is no cursor on the block.
          * @type {SVGElement}
          */
        cursorSvg: SVGElement;
    
        /**
          * Holds the markers svg element when the marker is attached to the block.
          * This is null if there is no marker on the block.
          * @type {SVGElement}
          */
        markerSvg: SVGElement;
    
        /**
          * Set the path generated by the renderer onto the respective SVG element.
          * @param {string} pathString The path.
          * @package
          */
        setPath(pathString: string): void;
    
        /**
          * Apply the stored colours to the block's path, taking into account whether
          * the paths belong to a shadow block.
          * @param {!Blockly.Block} block The source block.
          * @package
          */
        applyColour(block: Blockly.Block): void;
    
        /**
          * Update the style.
          * @param {!Blockly.Theme.BlockStyle} blockStyle The block style to use.
          * @package
          */
        setStyle(blockStyle: Blockly.Theme.BlockStyle): void;
    
        /**
          * Flip the SVG paths in RTL.
          * @package
          */
        flipRTL: any /*missing*/;
    
        /**
          * Add the cursor svg to this block's svg group.
          * @param {SVGElement} cursorSvg The svg root of the cursor to be added to the
          *     block svg group.
          * @package
          */
        setCursorSvg(cursorSvg: SVGElement): void;
    
        /**
          * Add the marker svg to this block's svg group.
          * @param {SVGElement} markerSvg The svg root of the marker to be added to the
          *     block svg group.
          * @package
          */
        setMarkerSvg(markerSvg: SVGElement): void;
    
        /**
          * Set whether the block shows a highlight or not.  Block highlighting is
          * often used to visually mark blocks currently being executed.
          * @param {boolean} highlighted True if highlighted.
          * @package
          */
        updateHighlighted(highlighted: boolean): void;
    
        /**
          * Add or remove styling showing that a block is selected.
          * @param {boolean} enable True if selection is enabled, false otherwise.
          * @package
          */
        updateSelected(enable: boolean): void;
    
        /**
          * Add or remove styling showing that a block is higlighted (not selected).
          * @param {boolean} enable True if highlight is enabled, false otherwise.
          * @package
          */
        updateHighlight(enable: boolean): void;
    
        /**
          * Add or remove styling showing that a block is higlighted (not selected).
          * @param {boolean} enable True if highlight is enabled, false otherwise.
          * @package
          */
        updateErrorHighlight(enable: boolean): void;
    
        /**
          * Add or remove styling showing that a block is dragged over a delete area.
          * @param {boolean} enable True if the block is being dragged over a delete
          *     area, false otherwise.
          * @package
          */
        updateDraggingDelete(enable: boolean): void;
    
        /**
          * Add or remove styling showing that a block is an insertion marker.
          * @param {boolean} enable True if the block is an insertion marker, false
          *     otherwise.
          * @package
          */
        updateInsertionMarker(enable: boolean): void;
    
        /**
          * Add or remove styling showing that a block is movable.
          * @param {boolean} enable True if the block is movable, false otherwise.
          * @package
          */
        updateMovable(enable: boolean): void;
    
        /**
          * Add or remove styling that shows that if the dragging block is dropped, this
          * block will be replaced.  If a shadow block, it will disappear.  Otherwise it
          * will bump.
          * @param {boolean} enable True if styling should be added.
          * @package
          */
        updateReplacementFade(enable: boolean): void;
    }
}
