
declare module Blockly.blockRendering {

    class PathObject extends PathObject__Class { }
    /** Fake class which should be extended to avoid inheriting static properties */
    class PathObject__Class implements Blockly.blockRendering.IPathObject  { 
    
            /**
             * An object that handles creating and setting each of the SVG elements
             * used by the renderer.
             * @param {!SVGElement} root The root SVG element.
             * @param {!Blockly.Theme.BlockStyle} style The style object to use for
             *     colouring.
             * @param {!Blockly.blockRendering.ConstantProvider} constants The renderer's
             *     constants.
             * @constructor
             * @implements {Blockly.blockRendering.IPathObject}
             * @package
             */
            constructor(root: SVGElement, style: Blockly.Theme.BlockStyle, constants: Blockly.blockRendering.ConstantProvider);
    
            /**
             * The renderer's constant provider.
             * @type {!Blockly.blockRendering.ConstantProvider}
             * @package
             */
            constants: Blockly.blockRendering.ConstantProvider;
    
            /**
             * The primary path of the block.
             * @type {!SVGElement}
             * @package
             */
            svgPath: SVGElement;
    
            /**
             * The style object to use when colouring block paths.
             * @type {!Blockly.Theme.BlockStyle}
             * @package
             */
            style: Blockly.Theme.BlockStyle;
    
            /**
             * Holds the cursors svg element when the cursor is attached to the block.
             * This is null if there is no cursor on the block.
             * @type {SVGElement}
             * @package
             */
            cursorSvg: SVGElement;
    
            /**
             * Holds the markers svg element when the marker is attached to the block.
             * This is null if there is no marker on the block.
             * @type {SVGElement}
             * @package
             */
            markerSvg: SVGElement;
    
            /**
             * Set the path generated by the renderer onto the respective SVG element.
             * @param {string} pathString The path.
             * @package
             */
            setPath(pathString: string): void;
    
            /**
             * Flip the SVG paths in RTL.
             * @package
             */
            flipRTL(): void;
    
            /**
             * Add the cursor svg to this block's svg group.
             * @param {SVGElement} cursorSvg The svg root of the cursor to be added to the
             *     block svg group.
             * @package
             */
            setCursorSvg(cursorSvg: SVGElement): void;
    
            /**
             * Add the marker svg to this block's svg group.
             * @param {SVGElement} markerSvg The svg root of the marker to be added to the
             *     block svg group.
             * @package
             */
            setMarkerSvg(markerSvg: SVGElement): void;
    
            /**
             * Apply the stored colours to the block's path, taking into account whether
             * the paths belong to a shadow block.
             * @param {!Blockly.Block} block The source block.
             * @package
             */
            applyColour(block: Blockly.Block): void;
    
            /**
             * Set the style.
             * @param {!Blockly.Theme.BlockStyle} blockStyle The block style to use.
             * @package
             */
            setStyle(blockStyle: Blockly.Theme.BlockStyle): void;
    
            /**
             * Add or remove the given CSS class on the path object's root SVG element.
             * @param {string} className The name of the class to add or remove
             * @param {boolean} add True if the class should be added.  False if it should
             *     be removed.
             * @protected
             */
            setClass_(className: string, add: boolean): void;
    
            /**
             * Set whether the block shows a highlight or not.  Block highlighting is
             * often used to visually mark blocks currently being executed.
             * @param {boolean} enable True if highlighted.
             * @package
             */
            updateHighlighted(enable: boolean): void;
    
            /**
             * Updates the look of the block to reflect a shadow state.
             * @param {boolean} shadow True if the block is a shadow block.
             * @protected
             */
            updateShadow_(shadow: boolean): void;
    
            /**
             * Updates the look of the block to reflect a disabled state.
             * @param {boolean} disabled True if disabled.
             * @protected
             */
            updateDisabled_(disabled: boolean): void;
    
            /**
             * Add or remove styling showing that a block is selected.
             * @param {boolean} enable True if selection is enabled, false otherwise.
             * @package
             */
            updateSelected(enable: boolean): void;
    
            /**
             * Add or remove styling showing that a block is higlighted (not selected).
             * @param {boolean} enable True if highlight is enabled, false otherwise.
             * @package
             */
            updateHighlight(enable: boolean): void;
    
            /**
             * Add or remove styling showing that a block is higlighted (not selected).
             * @param {boolean} enable True if highlight is enabled, false otherwise.
             * @package
             */
            updateErrorHighlight(enable: boolean): void;
    
            /**
             * Add or remove styling showing that a block is dragged over a delete area.
             * @param {boolean} enable True if the block is being dragged over a delete
             *     area, false otherwise.
             * @package
             */
            updateDraggingDelete(enable: boolean): void;
    
            /**
             * Add or remove styling showing that a block is an insertion marker.
             * @param {boolean} enable True if the block is an insertion marker, false
             *     otherwise.
             * @package
             */
            updateInsertionMarker(enable: boolean): void;
    
            /**
             * Add or remove styling showing that a block is movable.
             * @param {boolean} enable True if the block is movable, false otherwise.
             * @package
             */
            updateMovable(enable: boolean): void;
    
            /**
             * Add or remove styling that shows that if the dragging block is dropped, this
             * block will be replaced.  If a shadow block, it will disappear.  Otherwise it
             * will bump.
             * @param {boolean} enable True if styling should be added.
             * @package
             */
            updateReplacementFade(enable: boolean): void;
    
            /**
             * Add or remove styling that shows that if the dragging block is dropped, this
             * block will be connected to the input.
             * @param {Blockly.Connection} _conn The connection on the input to highlight.
             * @param {boolean} _enable True if styling should be added.
             * @package
             */
            updateShapeForInputHighlight(_conn: Blockly.Connection, _enable: boolean): void;
    } 
    
}
