
declare module Blockly.zelos {

    class PathObject extends PathObject__Class { }
    /** Fake class which should be extended to avoid inheriting static properties */
    class PathObject__Class extends Blockly.blockRendering.PathObject__Class  { 
    
            /**
             * An object that handles creating and setting each of the SVG elements
             * used by the renderer.
             * @param {!SVGElement} root The root SVG element.
             * @param {!Blockly.Theme.BlockStyle} style The style object to use for
             *     colouring.
             * @param {!Blockly.zelos.ConstantProvider} constants The renderer's constants.
             * @constructor
             * @extends {Blockly.blockRendering.PathObject}
             * @package
             */
            constructor(root: SVGElement, style: Blockly.Theme.BlockStyle, constants: Blockly.zelos.ConstantProvider);
    
            /**
             * The renderer's constant provider.
             * @type {!Blockly.zelos.ConstantProvider}
             */
            constants: Blockly.zelos.ConstantProvider;
    
            /**
             * The type of block's output connection shape.  This is set when a block with
             * an output connection is drawn.
             * @package
             */
            outputShapeType: any /*missing*/;
    
            /**
             * Updates error highlight state
             * @param {boolean} enable true / false to show red outline on the block
             */
            updateErrorHighlighted(enable: boolean): void;
    
            /**
             * Method that's called when the drawer is about to draw the block.
             * @package
             */
            beginDrawing(): void;
    
            /**
             * Method that's called when the drawer is done drawing.
             * @package
             */
            endDrawing(): void;
    
            /**
             * Set the path generated by the renderer for an outline path on the respective
             * outline path SVG element.
             * @param {string} name The input name.
             * @param {string} pathString The path.
             * @package
             */
            setOutlinePath(name: string, pathString: string): void;
    } 
    
}
